/**
 * Maps an original /assets/*.png path to its optimized WebP variant.
 * WebP files are pre-generated by scripts/optimize-images.mjs.
 *
 *  toWebp("/assets/kitchen-1.png")          -> "/assets/kitchen-1.webp"        (gallery / lightbox)
 *  toWebp("/assets/kitchen-1.png", "thumb") -> "/assets/kitchen-1-thumb.webp"  (grid cards)
 *
 * Always render inside a <picture> with the original path as <img src> fallback,
 * so anything without a generated WebP still loads.
 */
export const toWebp = (path: string, variant?: "thumb"): string =>
  path.replace(/\.(png|jpe?g)$/i, variant === "thumb" ? "-thumb.webp" : ".webp");
